services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  alembic:
    build: ./alembic_postgres
    restart: "no"
    depends_on:
      - postgres
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - alembic
