version: '1'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /mongo:/data/db
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
